<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lef_responsive_grid"
 *
 * Auto generated by Extension Builder 2015-03-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
  'title' => 'Bootstrap3 responsive grid',
  'description' => 'Responsive bootstrap3 grid layout, with support for automatic multi-resolution  images generation with retina and lazyload support.',
  'category' => 'fe',
  'author' => 'Stephen Leger',
  'author_email' => 'stephen@3dservices.ch',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'clearCacheOnLoad' => 0,
  'version' => '0.0.3',
  'constraints' => array(
    'depends' => array(
      'typo3' => '6.2.0-7.1.99',
      'gridelements' => '3.0.0-4.0.99',
      'css_styled_content' => '6.2.0-7.99.99',
      'lef_responsive_images' => '0.0.1-7.99.99',
    ),
    'conflicts' => array(
      'themes' => '2.3.0',
    ),
    'suggests' => array(
    ),
  ),
);